services:
  run-medaillon-pipeline:
    container_name: run-medaillon-pipeline
    build:
      dockerfile: ./Dockerfile
    ports:
      - 127.0.0.1:8888:20
    volumes:
      - E:/InvestmentPortfolioData:/mnt/data
    environment:
      DATA_DIR: "/mnt/data"
