services:
  dev-synapse:
    container_name: investment-portfolio-dev-container
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    ports:
      - 127.0.0.1:8888:20
    volumes:
      - ..:/code/
    environment:
      DEV: "True"
