name: Validate on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Validate on PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Run Ruff linter
        uses: ./.github/actions/ruff

      - name: Run tests
        run: |
          pip install -r requirements.txt
          pytest tests/
