name: Validate on PR

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  # JOB for detecting changes in packages
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            investment_etl: ./investment_etl/**
            investment_gui: ./investment_gui/**

  py-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Ruff linter
        uses: astral-sh/ruff-action@v3
      - run: ruff check

  py-test:
    runs-on: windows-latest
    needs: changes
    if: needs.changes.outputs.packages != '[]'
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install pipx and uvicorn
        run: |
          pip install pipx
          pipx ensurepath
          pipx install uv

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: |
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-uv-dev-${{ matrix.package }}-${{ format('{0}/pyproject.toml', matrix.package) }}
          restore-keys: |
            ${{ runner.os }}-uv-dev-${{ matrix.package }}-
            ${{ runner.os }}-uv-dev-

      - name: Install package for type checking
        run: |
          cd ${{ matrix.package }}
          uv sync --group dev

      - name: Run tests
        run: |
          python3 -m pytest ${{ matrix.package }}/tests/ --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

  static-type-check:
    runs-on: windows-latest
    needs: changes
    if: needs.changes.outputs.packages != '[]'
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install pipx and uvicorn
        run: |
          pip install pipx
          pipx ensurepath
          pipx install uv

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: |
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-uv-dev-${{ matrix.package }}-${{ hashFiles(format('{0}/pyproject.toml', matrix.package)) }}
          restore-keys: |
            ${{ runner.os }}-uv-dev-${{ matrix.package }}-
            ${{ runner.os }}-uv-dev-

      - name: Install package for type checking
        run: |
          cd ${{ matrix.package }}
          uv sync --group dev

      - name: Run if any of the listed files above is changed
        run: python 3 -m mypy --ignore-missing-imports ${{ matrix.package }}
