name: Validate on PR

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  py-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Ruff linter
        uses: astral-sh/ruff-action@v3
        with:
          src: >-
            ./src
            ./tests

      - run: ruff check

  py-test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/ --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

  static-type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - run: pip install mypy # you can pin your preferred version
      - run: mypy --install-types #install missing stubs

      - name: Get Python changed files
        id: changed-py-files
        uses: tj-actions/changed-files@v23
        with:
          files: |
            *.py
            **/*.py

      - name: Run if any of the listed files above is changed
        if: steps.changed-py-files.outputs.any_changed == 'true'
        run: mypy ${{ steps.changed-py-files.outputs.all_changed_files }} --ignore-missing-imports
