table FactDailyResult
	lineageTag: ba5c3b29-42cc-4eec-aa5e-10f69311dee4

	measure 'Current Total Profit' =
			
			VAR LatestDate = MAX(FactDailyResult[Date])
			RETURN
			CALCULATE(
			    SUM(FactDailyResult[Total_Profit]),
			    FactDailyResult[Date] = LatestDate
			)
		lineageTag: c619875d-7f31-4e0e-946d-ced2f5c0e79b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Current Currency Profit' =
			
			VAR LatestDate = MAX(FactDailyResult[Date])
			RETURN
			CALCULATE(
			    SUM(FactDailyResult[currency_profit]),
			    FactDailyResult[Date] = LatestDate
			)
		lineageTag: 7461d74d-0719-4a55-9c6e-9ac2fd99e146

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Current Option Profit' =
			
			VAR LatestDate = MAX(FactDailyResult[Date])
			RETURN
			CALCULATE(
			    SUM(FactDailyResult[product_profit]),
			    FactDailyResult[Date] = LatestDate
			)
		lineageTag: 51eeb6d2-91bb-49f8-9bd4-647d1fb35dc5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Value Forecast 5%/20y' =
			
			VAR r = 0.05
			VAR YearsPassed = 20
			RETURN
			[Current Total Value] * (1 + r) ^ YearsPassed
		lineageTag: 2f87a643-bb87-4c69-92bf-53226b36488a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Current Total Value' =
			
			VAR LatestDate = MAX(FactDailyResult[Date])
			RETURN
			CALCULATE(
			    SUM(FactDailyResult[total_value]),
			    FactDailyResult[Date] = LatestDate
			)
		lineageTag: 63f97a19-0926-40d1-9835-c8e466b564f2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Value Forecast 7%/20y' =
			
			VAR r = 0.07
			VAR YearsPassed = 20
			RETURN
			[Current Total Value] * (1 + r) ^ YearsPassed
		lineageTag: 5ca59dbf-2d8d-466a-bb17-41298a882a64

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Value Forecast Custom%/20y' =
			
			VAR r = VALUE( SUBSTITUTE([CAGR 5 Years %], "%", "") ) / 100
			VAR YearsPassed = 20
			RETURN
			[Current Total Value] * (1 + r) ^ YearsPassed
		lineageTag: 28c9a97a-d700-45ab-bf20-b089b3d51471

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Value Forecast CustomRate' =
			
			VAR PV = [Current Total Value]
			VAR r = VALUE(SUBSTITUTE([CAGR 5 Years %], "%", "")) / 100
			VAR BaseDate = MAX(FactDailyResult[Date])                 -- last actual date
			VAR CurrentDate = MAX('dimDate'[Date])             -- x-axis date
			VAR DaysPassed = DATEDIFF(BaseDate, CurrentDate, DAY)
			VAR YearsPassed = DIVIDE(DaysPassed, 365)      -- fractional years
			RETURN
			IF(
			    CurrentDate > BaseDate,
			    PV * (1 + r) ^ YearsPassed,
			    BLANK()
			)
		lineageTag: 334bcf78-9975-49a7-aba5-4a4013c066c5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Value Forecast 5%' =
			
			VAR PV = [Current Total Value]
			VAR r = 0.05
			VAR BaseDate = MAX(FactDailyResult[Date])                 -- last actual date
			VAR CurrentDate = MAX('dimDate'[Date])             -- x-axis date
			VAR DaysPassed = DATEDIFF(BaseDate, CurrentDate, DAY)
			VAR YearsPassed = DIVIDE(DaysPassed, 365)      -- fractional years
			RETURN
			IF(
			    CurrentDate > BaseDate,
			    PV * (1 + r) ^ YearsPassed,
			    BLANK()
			)
		lineageTag: c1682da5-7dd2-40f7-8fdf-6e020d2ac955

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Value Forecast 7%' =
			
			VAR PV = [Current Total Value]
			VAR r = 0.07
			VAR BaseDate = MAX(FactDailyResult[Date])                 -- last actual date
			VAR CurrentDate = MAX('dimDate'[Date])             -- x-axis date
			VAR DaysPassed = DATEDIFF(BaseDate, CurrentDate, DAY)
			VAR YearsPassed = DIVIDE(DaysPassed, 365)      -- fractional years
			RETURN
			IF(
			    CurrentDate > BaseDate,
			    PV * (1 + r) ^ YearsPassed,
			    BLANK()
			)
		lineageTag: 6b0d564d-06b2-447b-a104-ecaccf2407e1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column id
		dataType: string
		lineageTag: 8a86a163-7193-44cd-a47e-982d8afd5e73
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column date_id
		dataType: int64
		formatString: 0
		lineageTag: ede163b4-d06e-4625-964d-4d0cd9c547d4
		summarizeBy: sum
		sourceColumn: date_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4d2c3c7a-1edb-448e-996a-db231565c886
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 91996437-20b3-4970-b371-fad88f702c95
			defaultHierarchy: LocalDateTable_6f141cc2-8b3c-4770-b3f2-3a980c1a652a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column symbol
		dataType: string
		lineageTag: 0a1617de-9451-4e13-a8a4-c02134a6f621
		summarizeBy: none
		sourceColumn: symbol

		annotation SummarizationSetBy = Automatic

	column total_investment
		dataType: double
		lineageTag: d2f2f8f2-e360-4404-be18-a0096437cbd7
		summarizeBy: sum
		sourceColumn: total_investment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_value
		dataType: double
		lineageTag: 3ebf7a32-b632-4cb1-9eba-a45f199e862e
		summarizeBy: sum
		sourceColumn: total_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column number_owned
		dataType: double
		lineageTag: 6a8a8b3a-8c38-45f5-99ca-2bde45a1e135
		summarizeBy: sum
		sourceColumn: number_owned

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_buy_price
		dataType: double
		lineageTag: f2699f6c-fffa-45a9-8666-4db7870e2e99
		summarizeBy: sum
		sourceColumn: avg_buy_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column value_single_io
		dataType: double
		lineageTag: ef68f858-7db1-49b9-a7cc-bc16c5542df1
		summarizeBy: sum
		sourceColumn: value_single_io

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column product_profit
		dataType: double
		lineageTag: 640ffadf-d0a5-4125-998f-aea3020315bd
		summarizeBy: sum
		sourceColumn: product_profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column currency_profit
		dataType: double
		lineageTag: a57cf8f1-b45a-4094-a06c-89ffa9117866
		summarizeBy: sum
		sourceColumn: currency_profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_profit
		dataType: double
		lineageTag: 53ef8ccd-6093-47af-baa2-cae4f057fa3c
		summarizeBy: sum
		sourceColumn: total_profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FactDailyResult = m
		mode: import
		source =
				let
				    Source = Folder.Contents("E:\InvestmentPortfolioData\gold\fact_daily_result"),
				    ToDelta = DeltaLake.Table(Source)
				in
				    ToDelta

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

